version: "3.1"
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file: .env
    volumes:
      - ./data:/data
      - ../bitwarden/bitwarden.log:/var/log/bitwarden.log:ro
    restart: always
